version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "ChatService"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-l6r53guce7o"
s3_prefix = "ChatService"
region = "eu-central-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "BackendDependenciesStackName=\"BackendDependencies\""

